name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build_and_test:
    permissions:
      contents: write
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v3
      - uses: mlugg/setup-zig@v2
        with:
          version: master
      - run: uname -a
      - run: zig build
      - run: zig build docs
      - run: zig build test
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mlugg/setup-zig@v2
        with:
          version: master
      - run: zig fmt --check .
